name: secret_workflow_repository

on: [push]

jobs:
  show_secret_variable:
    runs-on: ubuntu-latest
    steps:
      - name: Step with a secret
        run: |
          echo "Hello, world!"
          echo "This is a secret value: ${{ secrets.SECRET_VALUE }}"
