name: secret_workflow_environment

on: [push]

jobs:
  show_secret_variable:
    environment: production_secret
    runs-on: ubuntu-latest
    steps:
      - name: Run Commands with a Secret
        run: |
          echo "Hello, world!"
          echo "This is a secret value: ${{ secrets.SECRET_VAL }}"
